#!/usr/bin/env bash
# This script runs an infinite loop and handles SIGTERM by printing "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
